version: 2.1

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - run-tests:
          filters:
            branches:
              only:
                - main
          requires:
            - build
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - run-tests

jobs:
  build:
    working_directory: ~/DevOpsProject23
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: 
          name: update-npm
          command: 'sudo npm install -g npm@8.1.4'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

  run-tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: run-tests
          command: npm run test

  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "export SERVER=\"$SERVER\"; export PRIVATE_KEY=\"$PRIVATE_KEY\"; rm -rf DevOpsProject23/; git clone https://github.com/CloByrne/DevOpsProject23.git; ls; cd DevOpsProject23; ls; source deploy.sh"
#deployment successful
